# Generated by Django 4.2.7 on 2024-01-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementpoint',
            name='type',
            field=models.CharField(default='PRODUCTION', max_length=200),
            preserve_default=False,
        ),
    ]
