# Generated by Django 5.0.1 on 2024-01-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementpoint',
            name='status',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurementpoint',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
