# Generated by Django 5.0.1 on 2024-01-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_measurementpoint_status_alter_measurementpoint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementpoint',
            name='identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
