# Generated by Django 5.0.1 on 2024-04-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_measurementpoint_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='board_member',
            field=models.BooleanField(default=False),
        ),
    ]
