# Generated by Django 5.0.1 on 2024-04-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_boardapproval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardapproval',
            old_name='date',
            new_name='date_time',
        ),
    ]
