# Generated by Django 5.0.1 on 2024-04-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_rename_date_boardapproval_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardapproval',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
