# Generated by Django 5.0.1 on 2024-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_boardapproval_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardapproval',
            name='answer',
            field=models.CharField(default='Ja', max_length=200),
            preserve_default=False,
        ),
    ]
