# Generated by Django 5.0.1 on 2024-04-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_boardapproval_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardapproval',
            name='new_member_approved',
            field=models.CharField(max_length=200),
        ),
    ]
