# Generated by Django 5.0.1 on 2024-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_memberapprovaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapprovaltask',
            name='date_time',
            field=models.DateTimeField(default='2024-02-01'),
            preserve_default=False,
        ),
    ]
