# Generated by Django 5.0.1 on 2024-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_boardapproval_new_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='hnr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='zip',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
