# Generated by Django 5.0.1 on 2024-07-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_member_welcome_message_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='welcome_message_sent_at',
        ),
        migrations.AddField(
            model_name='measurementpoint',
            name='welcome_message_sent_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
