# Generated by Django 5.0.1 on 2024-07-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_remove_member_welcome_message_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_since',
            field=models.DateField(null=True),
        ),
    ]
