# Generated by Django 5.0.1 on 2024-10-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_member_member_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('event_name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
