# Generated by Django 5.0.1 on 2024-12-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
