# Generated by Django 6.0.5 on 2026-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_openhabdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhabdb',
            name='port',
            field=models.IntegerField(default=5432),
        ),
    ]
