# Generated by Django 6.0.5 on 2026-05-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_alter_openhabdb_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementpoint',
            name='activation_remider_sent_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
