# Generated by Django 6.0.5 on 2026-05-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_measurementpoint_activation_remider_sent_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementpoint',
            old_name='activation_remider_sent_at',
            new_name='activation_reminder_sent_at',
        ),
    ]
