# Generated by Django 6.0.5 on 2026-07-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_openhabstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenhabStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.openhabstatus')),
            ],
            options={
                'verbose_name_plural': 'Openhab status histories',
                'indexes': [models.Index(fields=['status', 'time'], name='members_ope_status__9528ff_idx')],
            },
        ),
    ]
