# Generated by Django 6.0.5 on 2026-08-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_openhabstatushistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenhabDb',
        ),
    ]
