# Generated by Django 6.0.5 on 2026-08-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_delete_openhabdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('applicant_type', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_name', models.CharField(blank=True, default='', max_length=200)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('hnr', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=42)),
                ('account_name', models.CharField(max_length=200)),
                ('measurement_points', models.JSONField(default=list)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('accepted_sepa', models.BooleanField(default=False)),
                ('acknowledged_privacy_notice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessor_email', models.EmailField(max_length=254)),
                ('member_identifier', models.IntegerField()),
                ('endpoint', models.CharField(max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='members_mem_created_bdab11_idx')],
            },
        ),
    ]
