# Generated by hand on 2026-08-26 (Paket-Update vom Dashboard anfordern)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhabstatus',
            name='update_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
