# Generated by Django 6.0.5 on 2026-08-31 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_openhabstatus_update_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenhabCounterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('battery_grid_kwh', models.FloatField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.openhabstatus')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('status', 'day'), name='unique_counter_snapshot')],
            },
        ),
    ]
