# Generated by Django 5.0.1 on 2025-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature_2m', models.FloatField(help_text='Temperature at 2 meters (°C)')),
                ('cloud_cover', models.FloatField(help_text='Total cloud cover (%)')),
                ('direct_radiation', models.FloatField(help_text='Direct radiation (W/m²)')),
                ('rain', models.FloatField(help_text='Rain (mm)')),
                ('snowfall', models.FloatField(help_text='Snowfall (cm)')),
                ('cloud_cover_low', models.FloatField(help_text='Low-level cloud cover (%)')),
                ('cloud_cover_mid', models.FloatField(help_text='Mid-level cloud cover (%)')),
                ('cloud_cover_high', models.FloatField(help_text='High-level cloud cover (%)')),
            ],
        ),
    ]
