# Generated by Django 5.0.1 on 2025-04-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicweatherdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='historicweatherdata',
            name='timestamp',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
