# Generated by Django 5.0.1 on 2025-07-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_historicweatherdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature_2m', models.FloatField(help_text='°C')),
                ('cloud_cover', models.FloatField(help_text='%')),
                ('rain', models.FloatField(help_text='mm')),
                ('snowfall', models.FloatField(help_text='cm')),
                ('snow_depth', models.FloatField(help_text='m')),
                ('cloud_cover_low', models.FloatField(help_text='%')),
                ('cloud_cover_mid', models.FloatField(help_text='%')),
                ('cloud_cover_high', models.FloatField(help_text='%')),
                ('visibility', models.FloatField(help_text='m')),
                ('relative_humidity_2m', models.FloatField(help_text='%')),
                ('dew_point_2m', models.FloatField(help_text='°C')),
            ],
        ),
    ]
