# Generated by Django 5.0.1 on 2025-07-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='visibility',
        ),
    ]
