# Generated by Django 5.0.1 on 2025-07-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_remove_weatherdata_visibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricWeatherData',
        ),
    ]
