# Generated by Django 6.0.5 on 2026-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_delete_historicweatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='apparent_temperature',
            field=models.FloatField(help_text='°C (gefühlt)', null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='diffuse_radiation',
            field=models.FloatField(help_text='W/m²', null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='direct_normal_irradiance',
            field=models.FloatField(help_text='W/m²', null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='direct_radiation',
            field=models.FloatField(help_text='W/m²', null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='precipitation',
            field=models.FloatField(help_text='mm (Regen + Schauer + Schnee)', null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='shortwave_radiation',
            field=models.FloatField(help_text='W/m² (Globalstrahlung)', null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='snow_depth_water_equivalent',
            field=models.FloatField(help_text='mm', null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='sunshine_duration',
            field=models.FloatField(help_text='s pro Stunde', null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed_10m',
            field=models.FloatField(help_text='km/h', null=True),
        ),
    ]
