# Generated by Django 5.0.1 on 2024-01-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_measurementpoint_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('measurement_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.measurementpoint')),
                ('meter_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.metercode')),
            ],
        ),
    ]
