# Generated by Django 5.0.1 on 2024-01-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_measurementpoint_identifier'),
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('measurement_point', 'meter_code', 'timestamp', 'value'), name='unique_measurement'),
        ),
    ]
