# Generated by Django 5.0.1 on 2024-05-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_member_city_member_hnr_member_latitude_and_more'),
        ('metering', '0002_measurement_unique_measurement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='measurement',
            name='unique_measurement',
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('measurement_point', 'meter_code', 'timestamp'), name='unique_measurement'),
        ),
    ]
