# Generated by Django 5.0.1 on 2024-10-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0003_remove_measurement_unique_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
