# Generated by Django 6.0.5 on 2026-07-28 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0004_alter_measurement_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_version', models.CharField(max_length=50)),
                ('data_until', models.DateField()),
                ('horizon_start', models.DateTimeField()),
                ('horizon_end', models.DateTimeField()),
                ('training_intervals', models.IntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('consumption_kwh', models.FloatField()),
                ('consumption_kwh_p10', models.FloatField(null=True)),
                ('consumption_kwh_p90', models.FloatField(null=True)),
                ('generation_kwh', models.FloatField()),
                ('generation_kwh_p10', models.FloatField(null=True)),
                ('generation_kwh_p90', models.FloatField(null=True)),
                ('self_coverage_kwh', models.FloatField()),
                ('self_coverage_kwh_p10', models.FloatField(null=True)),
                ('self_coverage_kwh_p90', models.FloatField(null=True)),
                ('surplus_kwh', models.FloatField()),
                ('surplus_kwh_p10', models.FloatField(null=True)),
                ('surplus_kwh_p90', models.FloatField(null=True)),
                ('n_consumption_points', models.IntegerField()),
                ('n_generation_points', models.IntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='metering.energyforecastrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'timestamp'), name='unique_forecast_value')],
            },
        ),
    ]
