info:
  app:
    name: eegCentral
    version: '0.1'
    grailsVersion: 6.1.0
grails:
  plugin:
    springsecurity: # https://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#_configuration
      # https://stackoverflow.com/questions/34641681/grails-rest-spring-security-plugin-does-not-store-generated-token-using-gorm-in
      # http://grails-plugins.github.io/grails-spring-security-core/3.2.x/index.html
      useSecurityEventListener: true
      rest.token.storage.useGorm: true
      rest.token.storage.gorm.tokenDomainClassName: "eeg.central.AuthenticationToken"
      rest.token.storage.gorm.tokenValuePropertyName: "tokenValue"
      rest.token.storage.gorm.usernamePropertyName: "username"
      apf.storeLastUsername: true
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
  gorm:
    reactor:
      events: false

hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

environments:
  development:
    dataSource:
      #dbCreate: create-drop
      dbCreate: none
      #url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      username: eeg_central
      password: ${DB_PASSWORD}
      driverClassName: org.postgresql.Driver
      dialect: PostgreSQLDialect
      url: jdbc:postgresql://192.168.178.38:15432/eeg_central
  #test:
  #  dataSource:
  #    dbCreate: update
  #    url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  production:
    dataSource:
      dbCreate: none
      username: eeg_central
      password: ${DB_PASSWORD}
      driverClassName: org.postgresql.Driver
      dialect: PostgreSQLDialect
      url: jdbc:postgresql://192.168.178.38:15432/eeg_central
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED


