# Generated by Django 5.0.1 on 2024-09-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=34)),
                ('booking_date', models.DateField()),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_iban', models.CharField(max_length=34)),
                ('bic_swift', models.CharField(max_length=11)),
                ('partner_account_number', models.CharField(max_length=34)),
                ('bank_code', models.CharField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('booking_details', models.TextField()),
                ('booking_reference', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('highlight', models.BooleanField(default=False)),
                ('value_date', models.DateField()),
                ('virtual_card_number', models.CharField(blank=True, max_length=19, null=True)),
                ('paid_with', models.CharField(blank=True, max_length=255, null=True)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('mandate_id', models.CharField(blank=True, max_length=255, null=True)),
                ('creditor_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
