# Generated by Django 5.0.1 on 2024-09-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'partner_iban', 'amount', 'currency', 'booking_details', 'value_date', 'mandate_id', 'creditor_id', 'payment_reference', 'booking_reference')},
        ),
    ]
