# Generated by Django 5.0.1 on 2024-09-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='accounting.bookinglabel', verbose_name='Labels'),
        ),
    ]
