# Generated by Django 5.0.1 on 2024-09-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_bookinglabel_booking_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglabel',
            name='color',
            field=models.CharField(default='blue', max_length=20, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
