# Generated by Django 5.0.1 on 2024-09-22 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_bookinglabel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglabel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.bookinglabel'),
        ),
    ]
