# Generated by Django 5.0.1 on 2025-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_booking_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reverse_charge_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
